# Generated by Django 4.1.4 on 2023-01-16 06:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('expense', '0002_rename_expense_individualexpense'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IndividualExpense',
            new_name='IndividualExpenseModel',
        ),
        migrations.CreateModel(
            name='GroupExpenseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=200)),
                ('group_expense', models.DecimalField(decimal_places=2, max_digits=7)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to=settings.AUTH_USER_MODEL)),
                ('group_members', models.ManyToManyField(blank=True, related_name='group_members', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
